"""add organizations activities

Revision ID: 237922bd553b
Revises: 4e9f0239e6cd
Create Date: 2026-02-02 00:44:36.035329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237922bd553b'
down_revision: Union[str, Sequence[str], None] = '4e9f0239e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations_activities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('organizations_activities_activity_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('organizations_activities_organization_id_fkey')),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id', name=op.f('organizations_activities_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations_activities')
    # ### end Alembic commands ###
